export const eventData = [
  {
    id: 0,
    dateTime: "11/17/2022",
    eventName: "All-City Jazz Concert",
    time: "7:00PM",
    location: "South High Auditorium",
  },
  {
    id: 1,
    dateTime: "11/22/2022",
    eventName: "SE District Clinic Concert",
    time: "4:00PM",
    location: "East High Auditorium",
  },
  {
    id: 2,
    dateTime: "12/08/2022",
    eventName: "South Triad Winter Concert",
    time: "7:00PM",
    location: "Storey Gym",
  },
  {
    id: 3,
    dateTime: "1/15/2023",
    eventName: "All-State Band",
    time: "January 15 - 18",
    location: "Sheridan, WY",
  },
  // {
  //   id: 4,
  //   dateTime: "02/6/2023",
  //   eventName: "Casper Jazz Festival",
  //   time: "February 6 - 8",
  //   location: "Casper, WY",
  // },
  {
    id: 5,
    dateTime: "02/16/2023",
    eventName: "All-Northwest",
    time: "February 16 - 19",
    location: "Bellevue, WA",
  },
  {
    id: 6,
    dateTime: "02/21/2023",
    eventName: "Northwest Jazz Festival",
    time: "All Day",
    location: "Powell, WY",
  },
  {
    id: 7,
    dateTime: "02/27/2023",
    eventName: "UW Jazz Festival",
    time: "February 27 - 28",
    location: "Laramie, WY",
  },
  {
    id: 8,
    dateTime: "04/06/2023",
    eventName: "Spring Concert",
    time: "7:00PM",
    location: "South High Auditorium",
  },
  {
    id: 9,
    dateTime: "04/20/2023",
    eventName: "UNC Jazz Festival",
    time: "April 20 - 21",
    location: "Greeley, CO",
  },
  {
    id: 10,
    dateTime: "04/24/2023",
    eventName: "SE District Festival",
    time: "April 24 - 25",
    location: "Cheyenne, WY",
  },
  {
    id: 11,
    dateTime: "05/02/2023",
    eventName: "All-City Band",
    time: "7:00PM",
    location: "Storey Gym",
  },
  {
    id: 12,
    dateTime: "05/09/2023",
    eventName: "Final Concert",
    time: "7:00PM",
    location: "South High Auditorium",
  },
  {
    id: 13,
    dateTime: "05/18/2023",
    eventName: "Band Banquet",
    time: "6:00PM",
    location: "South High School",
  },
];