export const eventData = [
  {
    // todo ***change this information for all new events
    id: 0,
    dateTime: "11/17/2022",
    eventName: "All-City Jazz Concert",
    time: "7:00PM",
    location: "South High Auditorium",
    month: "November",
    day: 17,
    weekday: 2022,
  },
  {
    // todo ***change this information for all new events
    id: 1,
    dateTime: "11/22/2022",
    eventName: "SE District Clinic Concert",
    time: "4:00PM",
    location: "East High Auditorium",
    month: "November",
    day: 22,
    weekday: 2022,
  },
  {
    // todo ***change this information for all new events
    id: 2,
    dateTime: "12/08/2022",
    eventName: "South Triad Winter Concert",
    time: "7:00PM",
    location: "Storey Gym",
    month: "December",
    day: 8,
    weekday: 2022,
  },
  {
    // todo ***change this information for all new events
    id: 3,
    dateTime: "1/15/2023",
    eventName: "All-State Band",
    time: "January 15 - 18",
    location: "Sheridan, WY",
    month: "January",
    day: 15,
    weekday: 2022,
  },
  {
    // todo ***change this information for all new events
    id: 4,
    dateTime: "02/6/2023",
    eventName: "Casper Jazz Festival",
    time: "February 6 - 8",
    location: "Casper, WY",
    month: "February",
    day: 6,
    weekday: 2023,
  },
  {
    // todo ***change this information for all new events
    id: 5,
    dateTime: "02/16/2023",
    eventName: "All-Northwest",
    time: "February 16 - 19",
    location: "Bellevue, WA",
    month: "February",
    day: 16,
    weekday: 2023,
  },
  {
    // todo ***change this information for all new events
    id: 6,
    dateTime: "02/21/2023",
    eventName: "Northwest Jazz Festival",
    time: "All Day",
    location: "Powell, WY",
    month: "February",
    day: 21,
    weekday: 2023,
  },
  {
    // todo ***change this information for all new events
    id: 7,
    dateTime: "02/27/2023",
    eventName: "UW Jazz Festival",
    time: "February 27 - 28",
    location: "Laramie, WY",
    month: "February",
    day: 27,
    weekday: 2023,
  },
  {
    // todo ***change this information for all new events
    id: 8,
    dateTime: "04/06/2023",
    eventName: "Spring Concert",
    time: "7:00PM",
    location: "South High Auditorium",
    month: "April",
    day: 6,
    weekday: 2023,
  },
  {
    // todo ***change this information for all new events
    id: 9,
    dateTime: "04/20/2023",
    eventName: "UNC Jazz Festival",
    time: "April 20 - 21",
    location: "Greeley, CO",
    month: "April",
    day: 20,
    weekday: 2023,
  },
  {
    // todo ***change this information for all new events
    id: 10,
    dateTime: "04/24/2023",
    eventName: "SE District Festival",
    time: "April 24 - 25",
    location: "Cheyenne, WY",
    month: "April",
    day: 24,
    weekday: 2023,
  },
  {
    // todo ***change this information for all new events
    id: 11,
    dateTime: "05/02/2023",
    eventName: "All-City Band",
    time: "7:00PM",
    location: "Storey Gym",
    month: "May",
    day: 2,
    weekday: 2023,
  },
  {
    // todo ***change this information for all new events
    id: 12,
    dateTime: "05/09/2023",
    eventName: "Final Concert",
    time: "7:00PM",
    location: "South High Auditorium",
    month: "May",
    day: 9,
    weekday: 2023,
  },
  {
    // todo ***change this information for all new events
    id: 13,
    dateTime: "05/18/2023",
    eventName: "Band Banquet",
    time: "6:00PM",
    location: "South High School",
    month: "May",
    day: 18,
    weekday: 2023,
  },
];